### ISSUE TITLE
can you include screenshots plz 

### ISSUE THREAD

**Issue by BnourWej** [bradtraversy/ui_components#1]

**Comment by venkivijay** [comment]
@wejdeneBannour You can find the links to the original design on the readme file. I'll also add that here.
[Blog Post](https://uidesigndaily.com/posts/sketch-blog-cards-post-article-thumbnail-day-997)
[Login](https://uidesigndaily.com/posts/sketch-login-log-in-authentication-features-day-1022)
[Ads Manager](https://uidesigndaily.com/posts/sketch-ads-manager-table-list-day-1049)
